export const routePaths = {
  login: "/login",
  setup: "/setup",
  library: "/",
  discover: "/discover",
  search: "/search",
  downloads: "/downloads",
  indexers: "/indexers",
  downloaders: "/downloaders",
  settings: "/settings",
  calendar: "/calendar",
  wishlist: "/wishlist",
  xrel: "/xrel",
  rss: "/rss",
  stats: "/stats",
  logs: "/logs",
} as const;

export const appRoutePaths = [
  routePaths.login,
  routePaths.setup,
  routePaths.library,
  routePaths.discover,
  routePaths.search,
  routePaths.downloads,
  routePaths.indexers,
  routePaths.downloaders,
  routePaths.settings,
  routePaths.calendar,
  routePaths.wishlist,
  routePaths.xrel,
  routePaths.rss,
  routePaths.stats,
  routePaths.logs,
] as const;
